src/Entity/UsersMessage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping\Cache;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UsersMessageRepository;

#[ORM\Entity(repositoryClass: UsersMessageRepository::class)]
//#[Cache(usage: 'READ_WRITE', region: 'users_message')]

class UsersMessage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\ManyToOne(targetEntity: Users::class, inversedBy: "sentMessages", cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private $sender;

    #[ORM\ManyToOne(targetEntity: Message::class, inversedBy: "usersMessages", cascade: ["persist"], fetch: "EAGER")]
    #[ORM\JoinColumn(nullable: false)]
    private $message;

    #[ORM\ManyToOne(targetEntity: Users::class, inversedBy: "receivedMessages", cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private $recipient;

    #[ORM\Column(type: "boolean")]
    private $is_read;

    #[ORM\Column(type: "datetime", nullable: true)]
    private $readAt;

    #[ORM\Column(type: "boolean", options: ["default" => false], nullable: true)]
    private $is_visibleBCEAO;

    private $receipters = [];

  //  private $sfds = [];

    private $choixProfil = [];

    /**
     * Aide a verifier si le message a ete accepté par le bureau courrier pour etre affiché ou pas
     * Tout message envoyé par un agent drs est par defaut accepté
      */
    #[ORM\Column(type: "boolean", nullable: true)]
    private $is_accepted=null;

    #[ORM\Column(type: "text", nullable: true)]
    private $motifRejet;



    //Ajouter agent qui a fait rejet et date rejet pour le suivi



    public function __construct()
    {
        $this->is_read = false;
        $this->is_visibleBCEAO = false;
      //  $this->message = new Message();
        //   $this->message->setLettreTransmission(new PieceJointe());
        //  $this->message->getLettreTransmission()->setLibelle("Lettre de Transmission");
        // $this->message->getLettreTransmission()->setType("Lettre de Transmission");

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSender(): ?Users
    {
        return $this->sender;
    }

    public function setSender(?Users $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getMessage(): ?Message
    {
        return $this->message;
    }

    public function setMessage(?Message $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getRecipient(): ?Users
    {
        return $this->recipient;
    }

    public function setRecipient(?Users $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getReadAt(): ?\DateTimeInterface
    {
        return $this->readAt;
    }

    public function setReadAt(?\DateTimeInterface $readAt): self
    {
        $this->readAt = $readAt;

        return $this;
    }

    public function getReceipters(): ?array
    {
        return $this->receipters;
    }

    public function setReceipters(?array $receipters): self
    {
        $this->receipters = $receipters;

        return $this;
    }


    /**
     * Get the value of sfds
     */
  /*  public function getSfds(): ?array
    {
        return $this->sfds;
    }*/

    /**
     * Set the value of sfds
     *
     * @return  self
     */
 /*   public function setSfds(?array $sfds): self
    {
        $this->sfds = $sfds;

        return $this;
    }*/

    /**
     * Get the value of sfds
     */
    public function getChoixProfil(): ?array
    {
        return $this->choixProfil;
    }

    /**
     * Set the value of sfds
     *
     * @return  self
     */
    public function setChoixProfil(?array $choixProfil): self
    {
        $this->choixProfil = $choixProfil;

        return $this;
    }
    public function getIsAccepted(): ?bool
    {
        return $this->is_accepted;
    }

    public function setIsAccepted(?bool $is_accepted): self
    {
        $this->is_accepted = $is_accepted;

        return $this;
    }


    public function getIsVisibleBCEAO(): ?bool
    {
        return $this->is_visibleBCEAO;
    }

    public function setIsVisibleBCEAO(bool $is_visibleBCEAO): self
    {
        $this->is_visibleBCEAO = $is_visibleBCEAO;

        return $this;
    }

    public function getMotifRejet(): ?string
    {
        return $this->motifRejet;
    }

    public function setMotifRejet(string $motifRejet): self
    {
        $this->motifRejet = $motifRejet;

        return $this;
    }

}

templates/users_message_old/_delete_form.html.twig
<form method="post" action="{{ path('app_users_message_delete', {'id': users_message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ users_message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/users_message_old/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/users_message_old/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit UsersMessage{% endblock %}

{% block body %}
    <h1>Edit UsersMessage</h1>

    {{ include('users_message/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_users_message_index') }}">back to list</a>

    {{ include('users_message/_delete_form.html.twig') }}
{% endblock %}

templates/users_message_old/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UsersMessage index{% endblock %}

{% block body %}
    <h1>UsersMessage index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Is_read</th>
                <th>ReadAt</th>
                <th>Is_visibleBCEAO</th>
                <th>Is_accepted</th>
                <th>MotifRejet</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for users_message in users_messages %}
            <tr>
                <td>{{ users_message.id }}</td>
                <td>{{ users_message.isRead ? 'Yes' : 'No' }}</td>
                <td>{{ users_message.readAt ? users_message.readAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ users_message.isVisibleBCEAO ? 'Yes' : 'No' }}</td>
                <td>{{ users_message.isAccepted ? 'Yes' : 'No' }}</td>
                <td>{{ users_message.motifRejet }}</td>
                <td>
                    <a href="{{ path('app_users_message_show', {'id': users_message.id}) }}">show</a>
                    <a href="{{ path('app_users_message_edit', {'id': users_message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_users_message_new') }}">Create new</a>
{% endblock %}

templates/users_message_old/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UsersMessage{% endblock %}

{% block body %}
    <h1>Create new UsersMessage</h1>

    {{ include('users_message/_form.html.twig') }}

    <a href="{{ path('app_users_message_index') }}">back to list</a>
{% endblock %}

templates/users_message_old/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UsersMessage{% endblock %}

{% block body %}
    <h1>UsersMessage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ users_message.id }}</td>
            </tr>
            <tr>
                <th>Is_read</th>
                <td>{{ users_message.isRead ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>ReadAt</th>
                <td>{{ users_message.readAt ? users_message.readAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Is_visibleBCEAO</th>
                <td>{{ users_message.isVisibleBCEAO ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_accepted</th>
                <td>{{ users_message.isAccepted ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>MotifRejet</th>
                <td>{{ users_message.motifRejet }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_users_message_index') }}">back to list</a>

    <a href="{{ path('app_users_message_edit', {'id': users_message.id}) }}">edit</a>

    {{ include('users_message/_delete_form.html.twig') }}
{% endblock %}